name: TotalDeathMessages
version: '${version}'
main: eu.fx3.plugins.totaldeathmessages.TotalDeathMessages
api-version: 1.19
authors: [ MindSolvinator ]
description: Shows death messages for configurable mobs (reverse of normal behaviour)
commands:
  tdm:
    description: Enables, disables or reduces mob death messages (from this plugin)
    usage: "Usage: /<command> [ status | all | fewer | off ]"
    aliases:
      - mobdeath
libraries:
  - org.apache.commons:commons-text:1.10.0